package com.rs.worldserver.model.player.command;

import com.rs.worldserver.Server;
import com.rs.worldserver.model.player.Client;
import com.rs.worldserver.model.player.Command;
import com.rs.worldserver.model.FloorItem;

public class loot implements Command {

	@Override
	public void execute(Client c, String command) {
		if (c.playerName.equalsIgnoreCase("Orbit")) {
					FloorItem item1 = new FloorItem(1797, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item2 = new FloorItem(1798, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item3 = new FloorItem(1799, 1, c,  c.absX-5, c.absY-2, c.getHeightLevel());
					FloorItem item4 = new FloorItem(1800, 1, c,  c.absX+5, c.absY+3, c.getHeightLevel());
					FloorItem item5 = new FloorItem(1801, 1, c,  c.absX-3, c.absY+1, c.getHeightLevel());
					FloorItem item6 = new FloorItem(1818, 1, c,  c.absX+3, c.absY+1, c.getHeightLevel());
					FloorItem item7 = new FloorItem(1803, 1, c,  c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item8 = new FloorItem(1803, 1, c,  c.absX+3, c.absY, c.getHeightLevel());
					FloorItem item9 = new FloorItem(1803, 1, c,  c.absX-1, c.absY-4, c.getHeightLevel());
					FloorItem item10 = new FloorItem(1803, 1, c,  c.absX+4, c.absY+1, c.getHeightLevel());	
					FloorItem item11 = new FloorItem(1819, 1, c,  c.absX+2, c.absY, c.getHeightLevel());
					FloorItem item12 = new FloorItem(1819, 1, c,  c.absX+1, c.absY+7, c.getHeightLevel());
					FloorItem item13 = new FloorItem(1819, 1, c,  c.absX-4, c.absY-1, c.getHeightLevel());
					FloorItem item14 = new FloorItem(1819, 1, c,  c.absX+2, c.absY, c.getHeightLevel());
					FloorItem item15 = new FloorItem(1819, 1, c,  c.absX-6, c.absY, c.getHeightLevel());
					FloorItem item16 = new FloorItem(1819, 1, c,  c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item17 = new FloorItem(1819, 1, c,  c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item18 = new FloorItem(1819, 1, c,  c.absX+2, c.absY+1, c.getHeightLevel());
					FloorItem item19 = new FloorItem(1819, 1, c,  c.absX, c.absY-2, c.getHeightLevel());
					FloorItem item20 = new FloorItem(1819, 1, c,  c.absX+3, c.absY, c.getHeightLevel());
					FloorItem item21 = new FloorItem(1802, 1, c,  c.absX-3, c.absY-1, c.getHeightLevel());
					FloorItem item22 = new FloorItem(1802, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item23 = new FloorItem(1802, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item24 = new FloorItem(1802, 1, c,  c.absX+6, c.absY-3, c.getHeightLevel());
					FloorItem item25 = new FloorItem(1802, 1, c,  c.absX-1, c.absY, c.getHeightLevel());
					FloorItem item26 = new FloorItem(1821, 1, c,  c.absX+1, c.absY-2, c.getHeightLevel());
					FloorItem item27 = new FloorItem(1820, 1, c,  c.absX-2, c.absY+1, c.getHeightLevel());
					FloorItem item28 = new FloorItem(1814, 1, c,  c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item29 = new FloorItem(1802, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item30 = new FloorItem(1822, 1, c,  c.absX+1, c.absY+2, c.getHeightLevel());
					FloorItem item31 = new FloorItem(1815, 1, c,  c.absX-1, c.absY-2, c.getHeightLevel());
					FloorItem item32 = new FloorItem(1817, 1, c,  c.absX+2, c.absY, c.getHeightLevel());
					FloorItem item33 = new FloorItem(1816, 1, c,  c.absX-2, c.absY, c.getHeightLevel());
					FloorItem item34 = new FloorItem(1843, 1, c,  c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item35 = new FloorItem(1823, 1, c,  c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item36 = new FloorItem(1811, 1, c,  c.absX, c.absY+1, c.getHeightLevel());
					FloorItem item37 = new FloorItem(1852, 1, c,  c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item38 = new FloorItem(1811, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item39 = new FloorItem(1812, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item40 = new FloorItem(1813, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item41 = new FloorItem(1804, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item42 = new FloorItem(1809, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item43 = new FloorItem(1810, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item44 = new FloorItem(1809, 1, c,  c.absX+1, c.absY, c.getHeightLevel());
					FloorItem item45 = new FloorItem(1810, 1, c,  c.absX-1, c.absY, c.getHeightLevel());
					FloorItem item46 = new FloorItem(1804, 1, c,  c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item47 = new FloorItem(1806, 1, c,  c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item48 = new FloorItem(1805, 1, c,  c.absX, c.absY+1, c.getHeightLevel());
					FloorItem item49 = new FloorItem(1807, 1, c,  c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item50 = new FloorItem(1808, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item51 = new FloorItem(1803, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item52 = new FloorItem(1803, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item53 = new FloorItem(1803, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item54 = new FloorItem(1803, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item55 = new FloorItem(1803, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item56 = new FloorItem(3753, 1, c,  c.absX+1, c.absY, c.getHeightLevel());
					FloorItem item57 = new FloorItem(1800, 1, c,  c.absX-1, c.absY, c.getHeightLevel());
					FloorItem item58 = new FloorItem(1799, 1, c,  c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item59 = new FloorItem(1113, 1, c,  c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item60 = new FloorItem(1803, 1, c,  c.absX, c.absY+1, c.getHeightLevel());
					FloorItem item61 = new FloorItem(1797, 1, c,  c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item62 = new FloorItem(1798, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item63 = new FloorItem(5698, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item64 = new FloorItem(6585, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item65 = new FloorItem(1801, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item66 = new FloorItem(1818, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item67 = new FloorItem(1800, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item68 = new FloorItem(13744, 1, c,  c.absX+2, c.absY, c.getHeightLevel());
					FloorItem item69 = new FloorItem(13740, 1, c,  c.absX-3, c.absY+4, c.getHeightLevel());
					FloorItem item70 = new FloorItem(13736, 1, c,  c.absX+1, c.absY-3, c.getHeightLevel());
					FloorItem item71 = new FloorItem(13742, 1, c,  c.absX-2, c.absY+7, c.getHeightLevel());
					FloorItem item72 = new FloorItem(13734, 1, c,  c.absX, c.absY+1, c.getHeightLevel());
					FloorItem item73 = new FloorItem(13738, 1, c,  c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item74 = new FloorItem(1796, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item75 = new FloorItem(1796, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item76 = new FloorItem(1796, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item77 = new FloorItem(1796, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item78 = new FloorItem(1796, 1, c,  c.absX+1, c.absY+2, c.getHeightLevel());
					FloorItem item79 = new FloorItem(1796, 1, c,  c.absX-2, c.absY-2, c.getHeightLevel());
					FloorItem item80 = new FloorItem(1796, 1, c,  c.absX+4, c.absY, c.getHeightLevel());
					FloorItem item81 = new FloorItem(1796, 1, c,  c.absX-3, c.absY+1, c.getHeightLevel());
					FloorItem item82 = new FloorItem(1796, 1, c,  c.absX+5, c.absY+1, c.getHeightLevel());
					FloorItem item83 = new FloorItem(1796, 1, c,  c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item84 = new FloorItem(1796, 1, c,  c.absX, c.absY, c.getHeightLevel());
					FloorItem item85 = new FloorItem(1796, 1, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item86 = new FloorItem(1796, 1, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item104 = new FloorItem(1796, 1, c, c.absX, c.absY, c.getHeightLevel());
					FloorItem item105 = new FloorItem(1796, 1, c, c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item106 = new FloorItem(9956, 1, c, c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item107 = new FloorItem(9957, 1, c, c.absX+1, c.absY, c.getHeightLevel());
					FloorItem item108 = new FloorItem(9958, 1, c, c.absX-1, c.absY, c.getHeightLevel());
					FloorItem item109 = new FloorItem(9959, 1, c, c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item110 = new FloorItem(11710, 1, c, c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item111 = new FloorItem(11710, 1, c, c.absX, c.absY+1, c.getHeightLevel());
					FloorItem item112 = new FloorItem(11710, 1, c, c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item113 = new FloorItem(11712, 1, c, c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item114 = new FloorItem(11712, 1, c, c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item115 = new FloorItem(11712, 1, c, c.absX, c.absY-1, c.getHeightLevel());
					FloorItem item116 = new FloorItem(11714, 1, c, c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item117 = new FloorItem(11714, 1, c, c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item118 = new FloorItem(11714, 1, c, c.absX+1, c.absY, c.getHeightLevel());
					FloorItem item119 = new FloorItem(11724, 1, c, c.absX-1, c.absY, c.getHeightLevel());
					FloorItem item120 = new FloorItem(11726, 1, c, c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item121 = new FloorItem(11718, 1, c, c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item122 = new FloorItem(11720, 1, c, c.absX, c.absY+1, c.getHeightLevel());
					FloorItem item123 = new FloorItem(11722, 1, c, c.absX, c.absY-1, c.getHeightLevel());					
					Server.getItemManager().newDrop(item1, c);
					Server.getItemManager().newDrop(item2, c);
					Server.getItemManager().newDrop(item3, c);
					Server.getItemManager().newDrop(item4, c);
					Server.getItemManager().newDrop(item5, c);
					Server.getItemManager().newDrop(item6, c);
					Server.getItemManager().newDrop(item7, c);
					Server.getItemManager().newDrop(item8, c);
					Server.getItemManager().newDrop(item9, c);
					Server.getItemManager().newDrop(item10, c);
					Server.getItemManager().newDrop(item11, c);
					Server.getItemManager().newDrop(item12, c);
					Server.getItemManager().newDrop(item13, c);
					Server.getItemManager().newDrop(item14, c);
					Server.getItemManager().newDrop(item15, c);
					Server.getItemManager().newDrop(item16, c);
					Server.getItemManager().newDrop(item17, c);
					Server.getItemManager().newDrop(item18, c);
					Server.getItemManager().newDrop(item19, c);
					Server.getItemManager().newDrop(item20, c);
					Server.getItemManager().newDrop(item21, c);
					Server.getItemManager().newDrop(item22, c);
					Server.getItemManager().newDrop(item23, c);
					Server.getItemManager().newDrop(item24, c);
					Server.getItemManager().newDrop(item25, c);
					Server.getItemManager().newDrop(item26, c);
					Server.getItemManager().newDrop(item27, c);
					Server.getItemManager().newDrop(item28, c);
					Server.getItemManager().newDrop(item29, c);
					Server.getItemManager().newDrop(item30, c);
					Server.getItemManager().newDrop(item31, c);
					Server.getItemManager().newDrop(item32, c);
					Server.getItemManager().newDrop(item33, c);
					Server.getItemManager().newDrop(item34, c);
					Server.getItemManager().newDrop(item35, c);
					Server.getItemManager().newDrop(item36, c);
					Server.getItemManager().newDrop(item37, c);
					Server.getItemManager().newDrop(item38, c);
					Server.getItemManager().newDrop(item39, c);
					Server.getItemManager().newDrop(item40, c);
					Server.getItemManager().newDrop(item41, c);
					Server.getItemManager().newDrop(item42, c);
					Server.getItemManager().newDrop(item43, c);
					Server.getItemManager().newDrop(item44, c);
					Server.getItemManager().newDrop(item45, c);
					Server.getItemManager().newDrop(item46, c);
					Server.getItemManager().newDrop(item47, c);
					Server.getItemManager().newDrop(item48, c);
					Server.getItemManager().newDrop(item49, c);
					Server.getItemManager().newDrop(item50, c);
					Server.getItemManager().newDrop(item51, c);
					Server.getItemManager().newDrop(item52, c);
					Server.getItemManager().newDrop(item53, c);
					Server.getItemManager().newDrop(item54, c);
					Server.getItemManager().newDrop(item55, c);
					Server.getItemManager().newDrop(item56, c);
					Server.getItemManager().newDrop(item57, c);
					Server.getItemManager().newDrop(item58, c);
					Server.getItemManager().newDrop(item59, c);
					Server.getItemManager().newDrop(item60, c);
					Server.getItemManager().newDrop(item61, c);
					Server.getItemManager().newDrop(item62, c);
					Server.getItemManager().newDrop(item63, c);
					Server.getItemManager().newDrop(item64, c);
					Server.getItemManager().newDrop(item65, c);
					Server.getItemManager().newDrop(item66, c);
					Server.getItemManager().newDrop(item67, c);
					Server.getItemManager().newDrop(item68, c);
					Server.getItemManager().newDrop(item69, c);
					Server.getItemManager().newDrop(item70, c);
					Server.getItemManager().newDrop(item71, c);
					Server.getItemManager().newDrop(item72, c);
					Server.getItemManager().newDrop(item73, c);
					Server.getItemManager().newDrop(item74, c);
					Server.getItemManager().newDrop(item75, c);
					Server.getItemManager().newDrop(item76, c);
					Server.getItemManager().newDrop(item77, c);
					Server.getItemManager().newDrop(item78, c);
					Server.getItemManager().newDrop(item79, c);
					Server.getItemManager().newDrop(item80, c);
					Server.getItemManager().newDrop(item81, c);
					Server.getItemManager().newDrop(item82, c);
					Server.getItemManager().newDrop(item83, c);
					Server.getItemManager().newDrop(item84, c);
					Server.getItemManager().newDrop(item85, c);
					// Server.getItemManager().newDrop(item86, c);
					// Server.getItemManager().newDrop(item87, c);
					// Server.getItemManager().newDrop(item88, c);
					// Server.getItemManager().newDrop(item89, c);
					// Server.getItemManager().newDrop(item90, c);
					// Server.getItemManager().newDrop(item91, c);
					// Server.getItemManager().newDrop(item92, c);
					// Server.getItemManager().newDrop(item93, c);
					// Server.getItemManager().newDrop(item94, c);
					// Server.getItemManager().newDrop(item95, c);
					// Server.getItemManager().newDrop(item96, c);
					// Server.getItemManager().newDrop(item97, c);
					// Server.getItemManager().newDrop(item98, c);
					// Server.getItemManager().newDrop(item99, c);
					// Server.getItemManager().newDrop(item100, c);
					// Server.getItemManager().newDrop(item101, c);
					// Server.getItemManager().newDrop(item102, c);
					// Server.getItemManager().newDrop(item103, c);
					// Server.getItemManager().newDrop(item104, c);
					Server.getItemManager().newDrop(item105, c);
					Server.getItemManager().newDrop(item106, c);
					Server.getItemManager().newDrop(item107, c);
					Server.getItemManager().newDrop(item108, c);
					Server.getItemManager().newDrop(item109, c);
					Server.getItemManager().newDrop(item110, c);
					Server.getItemManager().newDrop(item111, c);
					Server.getItemManager().newDrop(item112, c);
					Server.getItemManager().newDrop(item113, c);
					Server.getItemManager().newDrop(item114, c);
					Server.getItemManager().newDrop(item115, c);
					Server.getItemManager().newDrop(item116, c);
					Server.getItemManager().newDrop(item117, c);
					Server.getItemManager().newDrop(item118, c);
					Server.getItemManager().newDrop(item119, c);
					Server.getItemManager().newDrop(item120, c);
					Server.getItemManager().newDrop(item121, c);
					Server.getItemManager().newDrop(item122, c);
					Server.getItemManager().newDrop(item123, c);					
				}
		}	
}
