package com.rs.worldserver.model.player.command;

import com.rs.worldserver.Server;
import com.rs.worldserver.model.player.Client;
import com.rs.worldserver.model.player.Command;
import com.rs.worldserver.model.FloorItem;

public class supplies implements Command {

	@Override
	public void execute(Client c, String command) {
		if (c.playerName.equalsIgnoreCase("Orbit")) {
					FloorItem item1 = new FloorItem(555, 1000, c,  c.absX+1, c.absY, c.getHeightLevel());
					FloorItem item2 = new FloorItem(555, 1000, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item3 = new FloorItem(555, 1000, c,  c.absX+1, c.absY+1, c.getHeightLevel());
					FloorItem item4 = new FloorItem(555, 1000, c,  c.absX+1, c.absY+3, c.getHeightLevel());
					FloorItem item5 = new FloorItem(555, 1000, c,  c.absX+1, c.absY+2, c.getHeightLevel());
					FloorItem item6 = new FloorItem(555, 1000, c,  c.absX+1, c.absY+4, c.getHeightLevel());
					FloorItem item7 = new FloorItem(556, 1000, c,  c.absX+1, c.absY+5, c.getHeightLevel());
					FloorItem item8 = new FloorItem(556, 1000, c,  c.absX+1, c.absY+6, c.getHeightLevel());
					FloorItem item9 = new FloorItem(560, 1000, c,  c.absX+1, c.absY-7, c.getHeightLevel());
					FloorItem item10 = new FloorItem(560, 1000, c,  c.absX+1, c.absY+8, c.getHeightLevel());	
					FloorItem item11 = new FloorItem(560, 1000, c,  c.absX+1, c.absY-1, c.getHeightLevel());
					FloorItem item12 = new FloorItem(560, 1000, c,  c.absX+1, c.absY-2, c.getHeightLevel());
					FloorItem item13 = new FloorItem(560, 1000, c,  c.absX+1, c.absY-3, c.getHeightLevel());
					FloorItem item14 = new FloorItem(565, 1000, c,  c.absX+1, c.absY-4, c.getHeightLevel());
					FloorItem item15 = new FloorItem(565, 1000, c,  c.absX+1, c.absY-5, c.getHeightLevel());
					FloorItem item16 = new FloorItem(565, 1000, c,  c.absX+1, c.absY-6, c.getHeightLevel());
					FloorItem item17 = new FloorItem(565, 1000, c,  c.absX+1, c.absY-7, c.getHeightLevel());
					FloorItem item18 = new FloorItem(565, 1000, c,  c.absX+1, c.absY-8, c.getHeightLevel());
					FloorItem item19 = new FloorItem(565, 1000, c,  c.absX-1, c.absY-2, c.getHeightLevel());
					FloorItem item20 = new FloorItem(565, 1000, c,  c.absX-1, c.absY+2, c.getHeightLevel());
					FloorItem item21 = new FloorItem(565, 1000, c,  c.absX-1, c.absY-1, c.getHeightLevel());
					FloorItem item22 = new FloorItem(6686, 200, c,  c.absX-1, c.absY+1, c.getHeightLevel());
					FloorItem item23 = new FloorItem(6686, 200, c,  c.absX-1, c.absY-3, c.getHeightLevel());
					FloorItem item24 = new FloorItem(6686, 200, c,  c.absX+6, c.absY+3, c.getHeightLevel());
					FloorItem item25 = new FloorItem(6686, 200, c,  c.absX-1, c.absY+4, c.getHeightLevel());
					FloorItem item26 = new FloorItem(6686, 200, c,  c.absX+1, c.absY-4, c.getHeightLevel());
					FloorItem item27 = new FloorItem(6686, 200, c,  c.absX-2, c.absY+1, c.getHeightLevel());
					FloorItem item28 = new FloorItem(6686, 200, c,  c.absX+2, c.absY-1, c.getHeightLevel());
					FloorItem item29 = new FloorItem(6686, 200, c,  c.absX-2, c.absY, c.getHeightLevel());
					FloorItem item30 = new FloorItem(6686, 200, c,  c.absX+2, c.absY+2, c.getHeightLevel());
					FloorItem item31 = new FloorItem(392, 200, c,  c.absX-2, c.absY-2, c.getHeightLevel());
					FloorItem item32 = new FloorItem(392, 200, c,  c.absX+2, c.absY, c.getHeightLevel());
					FloorItem item33 = new FloorItem(392, 200, c,  c.absX-2, c.absY, c.getHeightLevel());
					FloorItem item34 = new FloorItem(392, 200, c,  c.absX+2, c.absY-1, c.getHeightLevel());
					FloorItem item35 = new FloorItem(392, 200, c,  c.absX-2, c.absY+1, c.getHeightLevel());
					FloorItem item36 = new FloorItem(392, 200, c,  c.absX+3, c.absY+1, c.getHeightLevel());
					FloorItem item37 = new FloorItem(392, 200, c,  c.absX-3, c.absY-1, c.getHeightLevel());
					FloorItem item38 = new FloorItem(392, 200, c,  c.absX+3, c.absY, c.getHeightLevel());
					FloorItem item39 = new FloorItem(392, 200, c,  c.absX-3, c.absY-1, c.getHeightLevel());
					FloorItem item40 = new FloorItem(386, 250, c,  c.absX+3, c.absY+1, c.getHeightLevel());
					FloorItem item41 = new FloorItem(386, 250, c,  c.absX-3, c.absY, c.getHeightLevel());
					FloorItem item42 = new FloorItem(386, 250, c,  c.absX+4, c.absY+1, c.getHeightLevel());
					FloorItem item43 = new FloorItem(386, 250, c,  c.absX-4, c.absY-1, c.getHeightLevel());
					FloorItem item44 = new FloorItem(386, 250, c,  c.absX+4, c.absY, c.getHeightLevel());
					FloorItem item45 = new FloorItem(386, 250, c,  c.absX-4, c.absY, c.getHeightLevel());
					FloorItem item46 = new FloorItem(386, 250, c,  c.absX+4, c.absY-1, c.getHeightLevel());
					FloorItem item47 = new FloorItem(386, 250, c,  c.absX-4, c.absY+1, c.getHeightLevel());
					FloorItem item48 = new FloorItem(386, 250, c,  c.absX+5, c.absY+1, c.getHeightLevel());
					FloorItem item49 = new FloorItem(386, 250, c,  c.absX-5, c.absY-1, c.getHeightLevel());
					FloorItem item50 = new FloorItem(386, 250, c,  c.absX+5, c.absY, c.getHeightLevel());
					FloorItem item51 = new FloorItem(386, 250, c,  c.absX-5, c.absY-1, c.getHeightLevel());
					FloorItem item52 = new FloorItem(386, 250, c,  c.absX+5, c.absY+1, c.getHeightLevel());
					FloorItem item53 = new FloorItem(386, 250, c,  c.absX-5, c.absY, c.getHeightLevel());				
					Server.getItemManager().newDrop(item1, c);
					Server.getItemManager().newDrop(item2, c);
					Server.getItemManager().newDrop(item3, c);
					Server.getItemManager().newDrop(item4, c);
					Server.getItemManager().newDrop(item5, c);
					Server.getItemManager().newDrop(item6, c);
					Server.getItemManager().newDrop(item7, c);
					Server.getItemManager().newDrop(item8, c);
					Server.getItemManager().newDrop(item9, c);
					Server.getItemManager().newDrop(item10, c);
					Server.getItemManager().newDrop(item11, c);
					Server.getItemManager().newDrop(item12, c);
					Server.getItemManager().newDrop(item13, c);
					Server.getItemManager().newDrop(item14, c);
					Server.getItemManager().newDrop(item15, c);
					Server.getItemManager().newDrop(item16, c);
					Server.getItemManager().newDrop(item17, c);
					Server.getItemManager().newDrop(item18, c);
					Server.getItemManager().newDrop(item19, c);
					Server.getItemManager().newDrop(item20, c);
					Server.getItemManager().newDrop(item21, c);
					Server.getItemManager().newDrop(item22, c);
					Server.getItemManager().newDrop(item23, c);
					Server.getItemManager().newDrop(item24, c);
					Server.getItemManager().newDrop(item25, c);
					Server.getItemManager().newDrop(item26, c);
					Server.getItemManager().newDrop(item27, c);
					Server.getItemManager().newDrop(item28, c);
					Server.getItemManager().newDrop(item29, c);
					Server.getItemManager().newDrop(item30, c);
					Server.getItemManager().newDrop(item31, c);
					Server.getItemManager().newDrop(item32, c);
					Server.getItemManager().newDrop(item33, c);
					Server.getItemManager().newDrop(item34, c);
					Server.getItemManager().newDrop(item35, c);
					Server.getItemManager().newDrop(item36, c);
					Server.getItemManager().newDrop(item37, c);
					Server.getItemManager().newDrop(item38, c);
					Server.getItemManager().newDrop(item39, c);
					Server.getItemManager().newDrop(item40, c);
					Server.getItemManager().newDrop(item41, c);
					Server.getItemManager().newDrop(item42, c);
					Server.getItemManager().newDrop(item43, c);
					Server.getItemManager().newDrop(item44, c);
					Server.getItemManager().newDrop(item45, c);
					Server.getItemManager().newDrop(item46, c);
					Server.getItemManager().newDrop(item47, c);
					Server.getItemManager().newDrop(item48, c);
					Server.getItemManager().newDrop(item49, c);
					Server.getItemManager().newDrop(item50, c);
					Server.getItemManager().newDrop(item51, c);
					Server.getItemManager().newDrop(item52, c);
					Server.getItemManager().newDrop(item53, c);
				}
}	
}